name: WebRTC Build and Upload
on: 
  workflow_dispatch:
    inputs:
      webrtc_version:
        description: 'WebRTC Version'
        required: true
        type: string
      build_number:
        description: 'Build Number'
        required: true
        type: string
        default: '0'
jobs:
  build_and_upload:
    name: Build and Upload
    runs-on: macos-15
    timeout-minutes: 90
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
      - name: Run build script
        run: |
          export PATH="$PATH:$(pwd)/depot_tools"
          npx zx ./scripts/webrtc-build.mjs -v ${{ inputs.webrtc_version }} -n ${{ inputs.build_number }}
      - name: Upload
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          path: |
            build/WebRTC.xcframework/
            build/version.json
