name: WebRTC Build and Create Pull Request
on: 
  workflow_dispatch:
    inputs:
      webrtc_version:
        description: 'WebRTC Version'
        required: true
        type: string
      build_number:
        description: 'Build Number'
        required: true
        type: string
        default: '0'
jobs:
  build_and_pr:
    name: Build and Pull Request
    runs-on: macos-15
    timeout-minutes: 90
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
      - name: Run build script
        run: |
          export PATH="$PATH:$(pwd)/depot_tools"
          npx zx ./scripts/webrtc-build.mjs -v ${{ inputs.webrtc_version }} -n ${{ inputs.build_number }}
      - name: Copy artifacts
        run: |
          rm -rf WebRTC.xcframework
          cp -R build/WebRTC.xcframework .
          cp build/version.json .
      - name: Set GITHUB_ENV
        run: |
          WEBRTC_VERSION=$(cat version.json | jq -r .version.full)
          TIMESTAMP=$(date +%s)
          BRANCH_NAME="build-$WEBRTC_VERSION-$TIMESTAMP"

          echo "WEBRTC_VERSION=$WEBRTC_VERSION" >> $GITHUB_ENV
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
      - name: Commit
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          git switch -c $BRANCH_NAME

          git add WebRTC.xcframework version.json
          git commit -m "Build $WEBRTC_VERSION"
          git push origin $BRANCH_NAME
      - name: Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TITLE="WebRTC $WEBRTC_VERSION"
          BODY=$(cat <<- EOS
          ## Description

          WebRTC ${WEBRTC_VERSION} is built and the following files are updated.

          - \`WebRTC.xcframework\`
          - \`version.json\`

          ## Notes

          This PR is generated by GitHub Action.
          ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
          EOS
          )
          gh pr create --base main --head $BRANCH_NAME --title "$TITLE" --body "$BODY"
