name: Create Release
on:
  push:
    tags:
      - '*'
jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set GITHUB_ENV
        run: |
          NEXT_RELEASE=${{ github.ref_name }}
          WEBRTC_VERSION=$(cat version.json | jq -r .version.full)
          BRANCH_HEAD_NUMBER=$(cat version.json | jq -r .version.branch_head_number)
          COMMIT_HASH=$(cat version.json | jq -r .webrtc_commit_hash)
          COMMIT_POSITION=$(cat version.json | jq -r .version.commit_position)
          BUILD_NUMBER=$(cat version.json | jq -r .version.build_number)

          PREV_RELEASE=$(gh release list --limit 1 --json tagName | jq -r '.[].tagName')
          MERGE_COMMITS=$(git log ${PREV_RELEASE}...${NEXT_RELEASE} --merges --oneline | awk '{print $1}' | xargs)
          PR_LIST_TSV=$(gh pr list --state merged --search "${MERGE_COMMITS}" --json number,title | jq -r '.[] | [.number, .title] | join("\t")')

          echo "NEXT_RELEASE=$NEXT_RELEASE" >> $GITHUB_ENV
          echo "WEBRTC_VERSION=$WEBRTC_VERSION" >> $GITHUB_ENV
          echo "BRANCH_HEAD_NUMBER=$BRANCH_HEAD_NUMBER" >> $GITHUB_ENV
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          echo "COMMIT_POSITION=$COMMIT_POSITION" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
          echo "PR_LIST_TSV=$PR_LIST_TSV" >> $GITHUB_ENV
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMIT_HASH_SHORT=$(echo $COMMIT_HASH | cut -c 1-7)

          PR_URL_PREFIX="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/pull"
          PR_LIST_MD=$(echo $PR_LIST_TSV | awk -v FS="\t" \
              '{if ($2 !~ /^WebRTC [0-9]+\.[0-9]+\.[0-9]+$/) { printf "- %s [#%s]('$PR_URL_PREFIX'/%s)\n", $2, $1, $1 }}')

          NOTES=$(cat <<- EOS
          ## Build
          ### WebRTC

          - WebRTC Version: M${WEBRTC_VERSION}
              - Branch: [branch-heads/${BRANCH_HEAD_NUMBER}](https://chromium.googlesource.com/external/webrtc/+log/branch-heads/${BRANCH_HEAD_NUMBER})
              - Commit: [${COMMIT_HASH_SHORT}](https://chromium.googlesource.com/external/webrtc/+/$COMMIT_HASH)
          - Commit Position: ${COMMIT_POSITION}
          - Build Number: ${BUILD_NUMBER}

          ### Applied Patches

          - [disable_audio_input_interface](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/blob/${WEBRTC_VERSION}/patches/disable_audio_input_interface.patch) 

          ## Development

          ${PR_LIST_MD}
          EOS
          )
          gh release create $NEXT_RELEASE --title "$NEXT_RELEASE" --notes "$NOTES"
